#include <acm/bs.h>

char const * acm_shipnm(acm_shipid const _ship) {
	switch (_ship) {
	case acm_shipid_add:
		return "Adder";
	case acm_shipid_ana:
		return "Anaconda";
	case acm_shipid_asp:
		return "Asp";
	case acm_shipid_boa:
		return "Boa";
	case acm_shipid_cob:
		return "Cobra";
	case acm_shipid_con:
		return "Constrictor";
	case acm_shipid_cou:
		return "Courier";
	case acm_shipid_cyg:
		return "Cygnus";
	case acm_shipid_dov:
		return "Dove";
	case acm_shipid_eag:
		return "Eagle";
	case acm_shipid_falc:
		return "Falcon";
	case acm_shipid_fer:
		return "Fer-de-lance";
	case acm_shipid_frei:
		return "Freighter";
	case acm_shipid_geck:
		return "Gecko";
	case acm_shipid_haul:
		return "Hauler";
	case acm_shipid_hawk:
		return "Hawk";
	case acm_shipid_keel:
		return "Keelback";
	case acm_shipid_kes:
		return "Kestral";
	case acm_shipid_krait:
		return "Krait";
	case acm_shipid_lift:
		return "Lifter";
	case acm_shipid_lion:
		return "Lion";
	case acm_shipid_mamba:
		return "Mamba";
	case acm_shipid_moray:
		return "Moray";
	case acm_shipid_osp:
		return "Osprey";
	case acm_shipid_pan:
		return "Panther";
	case acm_shipid_puma:
		return "Puma";
	case acm_shipid_py:
		return "Python";
	case acm_shipid_shut:
		return "Shuttle";
	case acm_shipid_side:
		return "Sidewinder";
	case acm_shipid_tran:
		return "Transporter";
	case acm_shipid_vip:
		return "Viper";
	case acm_shipid_vult:
		return "Vulture";
	}
}
